# Generated by Django 3.0.6 on 2020-10-17 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_num', models.CharField(max_length=16)),
                ('place', models.CharField(max_length=512)),
                ('safety_desc', models.CharField(max_length=1024)),
            ],
        ),
    ]
