# Generated by Django 3.0.6 on 2020-10-17 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefectType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Subdivision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supports', to='common.Object')),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='order_num',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='place',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='safety_desc',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.CreateModel(
            name='SupportDefect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='support_defects', to='common.DefectType')),
                ('support', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='defects', to='common.Support')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='object',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='common.Object'),
        ),
        migrations.AddField(
            model_name='order',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='common.Organization'),
        ),
        migrations.AddField(
            model_name='order',
            name='subdivision',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='common.Subdivision'),
        ),
    ]
