# Generated by Django 3.0.6 on 2020-10-17 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20201017_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='latitude',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='object',
            name='longitude',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
    ]
