# Generated by Django 3.0.6 on 2020-10-17 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_auto_20201017_1242'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='place',
            new_name='range',
        ),
    ]
