# Generated by Django 3.0.6 on 2020-10-17 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_auto_20201017_1315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='role',
        ),
        migrations.DeleteModel(
            name='WorkerRole',
        ),
    ]
