# Generated by Django 3.0.6 on 2020-10-17 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_auto_20201017_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportdefect',
            name='defect_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='support_defects', to='common.DefectType'),
        ),
        migrations.AlterField(
            model_name='supportdefect',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='defects', to='common.Order'),
        ),
    ]
