# Generated by Django 3.0.6 on 2020-10-17 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_auto_20201017_1635'),
    ]

    operations = [
        migrations.CreateModel(
            name='Defect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('defect_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='defects', to='common.DefectType')),
            ],
        ),
        migrations.CreateModel(
            name='Subobject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subobjects', to='common.Object')),
            ],
        ),
        migrations.RemoveField(
            model_name='supportdefect',
            name='defect_type',
        ),
        migrations.RemoveField(
            model_name='supportdefect',
            name='order',
        ),
        migrations.RemoveField(
            model_name='supportdefect',
            name='support',
        ),
        migrations.RemoveField(
            model_name='order',
            name='range',
        ),
        migrations.DeleteModel(
            name='Support',
        ),
        migrations.DeleteModel(
            name='SupportDefect',
        ),
        migrations.AddField(
            model_name='defect',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='defects', to='common.Order'),
        ),
        migrations.AddField(
            model_name='defect',
            name='subobject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='defects', to='common.Subobject'),
        ),
    ]
