# Generated by Django 3.0.6 on 2020-10-17 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_auto_20201017_1639'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='common.Order')),
            ],),
        migrations.AddField(
            model_name='defect',
            name='report',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='defects', to='common.Report'),
        ),
    ]
