# Generated by Django 3.0.6 on 2020-10-17 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_auto_20201017_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='defect',
            name='report',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='defects', to='common.Report'),
        ),
        migrations.AddField(
            model_name='subobject',
            name='latitude',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='subobject',
            name='longitude',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
    ]
