# Generated by Django 3.0.6 on 2020-10-17 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_auto_20201017_2155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='instructions_given',
        ),
        migrations.RemoveField(
            model_name='order',
            name='instructions_received',
        ),
        migrations.RemoveField(
            model_name='order',
            name='job_finished',
        ),
        migrations.RemoveField(
            model_name='order',
            name='job_started',
        ),
    ]
