# Generated by Django 3.0.6 on 2020-10-17 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0012_auto_20201017_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subobject',
            name='title',
            field=models.CharField(max_length=128),
        ),
    ]
