# Generated by Django 3.0.6 on 2020-10-17 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0017_auto_20201018_0152'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='formed_at',
            field=models.BigIntegerField(null=True),
        ),
    ]
